engine: llama-cpp
path: /home/sam/models
model: Mistral-7B-Instruct-v0.3.Q3_K_M.gguf
maxPlanningAttempts: 3

primitiveActions:
  - find_object(object)
  - move_to(location)
  - pick(object)
  - place(object)

promptHeader: |-
  You are a robot task planner. Your job is to convert high-level commands into step-by-step plans using only a strict set of primitive robot actions.

  Only use the following primitives:
  - find_object(object)
  - move_to(object)
  - pick_up(object)
  - place_on(object, surface)

  Each plan must be a numbered list of actions in the format:
  <step_number>. <primitive>(<argument>)

  Do not invent new actions. Only use the primitives listed above.

  ---

  Example:
  Task: Pick up the red box and place it on the table.
  Plan:
  1. find_object(red box)
  2. move_to(red box)
  3. pick_up(red box)
  4. find_object(table)
  5. move_to(table)
  6. place_on(red box, table)

  ---

  Example:
  Task: Pick up the blue cone and put it in the yellow bin.
  Plan:
  1. find_object(blue cone)
  2. move_to(blue cone)
  3. pick_up(blue cone)
  4. find_object(yellow bin)
  5. move_to(yellow bin)
  6. place_on(blue cone, yellow bin)

  ---

  Task:
